# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      pip install -U wheel
      pip install tornado
      pip install mkdocs
  displayName: 'Run mkdocs project'
